// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR-VqrxV25Hdu8y_19D1HtY9AznfIZB20',
    appId: '1:40470999039:web:3e5b2d3d3862ffd95881ca',
    messagingSenderId: '40470999039',
    projectId: 'interlinearplus-f2233',
    authDomain: 'interlinearplus-f2233.firebaseapp.com',
    storageBucket: 'interlinearplus-f2233.appspot.com',
    measurementId: 'G-2R178PFZYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDELmQeoR-Kf393nlG0Y05W2iUyfarFSyw',
    appId: '1:40470999039:android:317b8bffded77a5b5881ca',
    messagingSenderId: '40470999039',
    projectId: 'interlinearplus-f2233',
    storageBucket: 'interlinearplus-f2233.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIE-PSaZTHAVliXNYYiWwufeF0xmdZy8g',
    appId: '1:40470999039:ios:e81786db0c39eca95881ca',
    messagingSenderId: '40470999039',
    projectId: 'interlinearplus-f2233',
    storageBucket: 'interlinearplus-f2233.appspot.com',
    iosBundleId: 'com.example.interlinearplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIE-PSaZTHAVliXNYYiWwufeF0xmdZy8g',
    appId: '1:40470999039:ios:c4c2f47c4a6ed4525881ca',
    messagingSenderId: '40470999039',
    projectId: 'interlinearplus-f2233',
    storageBucket: 'interlinearplus-f2233.appspot.com',
    iosBundleId: 'com.example.interlinearplus.RunnerTests',
  );
}
